# Generated by Django 5.2.11 on 2026-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgente'), ('important', 'Importante'), ('later', 'Mais Tarde')], default='later', max_length=20),
        ),
    ]
